//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionHosting.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLLOG()
        {
            this.TBLDOMAIN = new HashSet<TBLDOMAIN>();
        }
    
        public int userID { get; set; }
        public string userNAME { get; set; }
        public string userPASS { get; set; }
        public Nullable<int> rolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDOMAIN> TBLDOMAIN { get; set; }
        public virtual TBLROLS TBLROLS { get; set; }
    }
}
